const saleConstants = {
  REQUEST_CREATE_EDIT_SALE: 'wolfapp/sale/REQUEST_CREATE_EDIT_SALE',
  SUCCESS_CREATE_EDIT_SALE: 'wolfapp/sale/SUCCESS_CREATE_EDIT_SALE',
  FAILURE_CREATE_EDIT_SALE: 'wolfapp/sale/FAILURE_CREATE_EDIT_SALE',
  REQUEST_SALES_LIST: 'wolfapp/sale/REQUEST_SALES_LIST',
  RESET_SALES_LIST: 'wolfapp/sale/RESET_SALES_LIST',
  SET_SALES_LIST: 'wolfapp/sale/SET_SALES_LIST',
  SUCCESS_SALES_LIST: 'wolfapp/sale/SUCCESS_SALES_LIST',
  FAILURE_SALES_LIST: 'wolfapp/sale/FAILURE_SALES_LIST',
  REQUEST_FETCH_SALE: 'wolfapp/sale/REQUEST_FETCH_SALE',
  SUCCESS_FETCH_SALE: 'wolfapp/sale/SUCCESS_FETCH_SALE',
  FAILURE_FETCH_SALE: 'wolfapp/sale/FAILURE_FETCH_SALE',
  REQUEST_DELETE_SALE: 'wolfapp/sale/REQUEST_DELETE_SALE',
  SUCCESS_DELETE_SALE: 'wolfapp/sale/SUCCESS_DELETE_SALE',
  FAILURE_DELETE_SALE: 'wolfapp/sale/FAILURE_DELETE_SALE',
  RESET_SALE: 'wolfapp/sale/RESET_SALE',
  SET_SALE_LOADING: 'wolfapp/sale/SET_SALE_LOADING',
  SET_SALES_LOADING: 'wolfapp/sale/SET_SALES_LOADING',
};

export default saleConstants;
