const orderConstants = {
  REQUEST_CREATE_EDIT_ORDER: 'wolfapp/order/REQUEST_CREATE_EDIT_ORDER',
  SUCCESS_CREATE_EDIT_ORDER: 'wolfapp/order/SUCCESS_CREATE_EDIT_ORDER',
  FAILURE_CREATE_EDIT_ORDER: 'wolfapp/order/FAILURE_CREATE_EDIT_ORDER',
  REQUEST_ORDERS_LIST: 'wolfapp/order/REQUEST_ORDERS_LIST',
  RESET_ORDERS_LIST: 'wolfapp/order/RESET_ORDERS_LIST',
  SET_ORDERS_LIST: 'wolfapp/order/SET_ORDERS_LIST',
  SUCCESS_ORDERS_LIST: 'wolfapp/order/SUCCESS_ORDERS_LIST',
  FAILURE_ORDERS_LIST: 'wolfapp/order/FAILURE_ORDERS_LIST',
  REQUEST_FETCH_ORDER: 'wolfapp/order/REQUEST_FETCH_ORDER',
  SUCCESS_FETCH_ORDER: 'wolfapp/order/SUCCESS_FETCH_ORDER',
  FAILURE_FETCH_ORDER: 'wolfapp/order/FAILURE_FETCH_ORDER',
  REQUEST_DELETE_ORDER: 'wolfapp/order/REQUEST_DELETE_ORDER',
  SUCCESS_DELETE_ORDER: 'wolfapp/order/SUCCESS_DELETE_ORDER',
  FAILURE_DELETE_ORDER: 'wolfapp/order/FAILURE_DELETE_ORDER',
  RESET_ORDER: 'wolfapp/order/RESET_ORDER',
  SET_ORDER_LOADING: 'wolfapp/order/SET_ORDER_LOADING',
  SET_ORDERS_LOADING: 'wolfapp/order/SET_ORDERS_LOADING',
};

export default orderConstants;
