const customerConstants = {
  REQUEST_LOCALITIES: 'wolfapp/customer/REQUEST_LOCALITIES',
  SET_LOCALITIES: 'wolfapp/customer/SET_LOCALITIES',
  REQUEST_CREATE_EDIT_CUSTOMER: 'wolfapp/customer/REQUEST_CREATE_EDIT_CUSTOMER',
  SUCCESS_CREATE_EDIT_CUSTOMER: 'wolfapp/customer/SUCCESS_CREATE_EDIT_CUSTOMER',
  FAILURE_CREATE_EDIT_CUSTOMER: 'wolfapp/customer/FAILURE_CREATE_EDIT_CUSTOMER',
  REQUEST_CUSTOMERS_LIST: 'wolfapp/customer/REQUEST_CUSTOMERS_LIST',
  RESET_CUSTOMERS_LIST: 'wolfapp/customer/RESET_CUSTOMERS_LIST',
  SET_CUSTOMERS_LIST: 'wolfapp/customer/SET_CUSTOMERS_LIST',
  SUCCESS_CUSTOMERS_LIST: 'wolfapp/customer/SUCCESS_CUSTOMERS_LIST',
  FAILURE_CUSTOMERS_LIST: 'wolfapp/customer/FAILURE_CUSTOMERS_LIST',
  REQUEST_FETCH_CUSTOMER: 'wolfapp/customer/REQUEST_FETCH_CUSTOMER',
  SUCCESS_FETCH_CUSTOMER: 'wolfapp/customer/SUCCESS_FETCH_CUSTOMER',
  FAILURE_FETCH_CUSTOMER: 'wolfapp/customer/FAILURE_FETCH_CUSTOMER',
  REQUEST_DELETE_CUSTOMER: 'wolfapp/customer/REQUEST_DELETE_CUSTOMER',
  SUCCESS_DELETE_CUSTOMER: 'wolfapp/customer/SUCCESS_DELETE_CUSTOMER',
  FAILURE_DELETE_CUSTOMER: 'wolfapp/customer/FAILURE_DELETE_CUSTOMER',
  RESET_CUSTOMER: 'wolfapp/customer/RESET_CUSTOMER',
  SET_CUSTOMER_LOADING: 'wolfapp/customer/SET_CUSTOMER_LOADING',
  SET_CUSTOMERS_LOADING: 'wolfapp/customer/SET_CUSTOMERS_LOADING',
};

export default customerConstants;
